# Generated by Django 5.2.2 on 2025-06-14 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('telephone1', models.CharField(max_length=20)),
                ('telephone2', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_adhesion', models.DateField()),
                ('etat', models.CharField(choices=[('Actif', 'Actif'), ('Suspendu', 'Suspendu'), ('Décédé', 'Décédé')], max_length=10)),
                ('fonction', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom de l'exercice (ex\u202f: 2023)", max_length=100, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('cloture', models.BooleanField(default=False, help_text='L’exercice est-il clôturé ?')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciceArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('archive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParametreCotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cotisation', models.CharField(choices=[('Mensuelle', 'Mensuelle'), ('Deces_H', 'Décès Homme'), ('Deces_F', 'Décès Femme'), ('Exceptionnelle', 'Exceptionnelle'), ('Projet', 'Projet')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_effet', models.DateField()),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Deces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_deces', models.DateField()),
                ('observations', models.CharField(blank=True, max_length=200, null=True)),
                ('adherent_defunt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deces', to='mutuelle.adherent')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mutuelle.section')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mutuelle.section')),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('libelle', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_depense', models.CharField(choices=[('Fonctionnement', 'Fonctionnement'), ('Décès', 'Décès'), ('Projet', 'Projet/Exceptionnelle')], max_length=30)),
                ('observation', models.CharField(blank=True, max_length=200, null=True)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='mutuelle.exercice')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mutuelle.section')),
            ],
        ),
        migrations.CreateModel(
            name='CotisationMensuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=20)),
                ('annee', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutuelle.adherent')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mutuelle.section')),
            ],
        ),
        migrations.CreateModel(
            name='CotisationExceptionnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('date_debut', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('projet', models.CharField(blank=True, max_length=200, null=True)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutuelle.adherent')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotisations', to='mutuelle.exercice')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mutuelle.section')),
            ],
        ),
        migrations.CreateModel(
            name='CotisationDeces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations_deces', to='mutuelle.adherent')),
                ('deces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='mutuelle.deces')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mutuelle.section')),
            ],
        ),
        migrations.AddField(
            model_name='adherent',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mutuelle.section'),
        ),
    ]
